#!/bin/bash
FILE=/tmp/custom-command-toggle-test
PENDING=/tmp/custom-command-toggle-test.pending


start() {
    touch $PENDING 
    (sleep 20;
    touch $FILE;
    rm -f $PENDING) &
}

stop() {
    rm -f $FILE
}

status() {
    if [ -f $PENDING ]; then
        echo "Custom Command Toggle is starting"
        exit 2
    fi
    if [ -f $FILE ]; then
        echo "Custom Command Toggle is running"
        exit 0
    else
        echo "Custom Command Toggle is not running"
        exit 1
    fi
}


"$@"
